### PR TITLE
Synchronize Hoa repository with the old one

### PR DESCRIPTION
**Pull request by stevenremot**
This pull request is part of the issue #1 .

It updates the code to the latest version of `hoa-pp-mode`, updates the `README`, uses the Hoa project's license, and add a `.gitignore` and a `Cask` file ([Cask](https://github.com/cask/cask) is a project management tool for Emacs, it handles dependencies and automates some tasks)

### CODE REVIEW

**Comment by Hywan** [comment]
Is it ready for a merge?

**Comment by stevenremot** [comment]
Yes it is, it just won't be the last step to close this issue.

**Comment by Hywan** [comment]
Regarding https://github.com/hoaproject/Contributions-Emacs-Pp/issues/1#issuecomment-141423503, I assume yes.

**Comment by Hywan** [comment]
@stevenremot Ok.

**Pull request merged**
