### PR TITLE
Add Imenu in screenshot

### PR DESCRIPTION
**Pull request by stevenremot**
Change the README screenshot to display a use case of Imenu

### CODE REVIEW

**Comment by Hywan** [comment]
Fixed in https://github.com/hoaproject/Contributions-Emacs-Pp/commit/12fa65a93c92904744b94a8f311d50ad2468fba8. I applied pngcrush.com on the resulting screenshot to save disk.

**Comment by Hywan** [comment]
Can we add a new tag now?

**Comment by stevenremot** [comment]
Thanks for the PNG processing! I will bump the version to 0.3.0 and add the related tag. Are you ok with it?

**Comment by Hywan** [comment]
Yup.

**Comment by Hywan** [comment]
You have permissions to write directly on `git@git.hoa-project.net:Contributions/Emacs/Pp`. Do you want to learn how to do that? If yes, come on IRC.

**Pull request closed without merging**
